-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 11:08:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Reservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Reservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Reservas` DEFAULT CHARACTER SET utf8 ;
USE `Reservas` ;

-- -----------------------------------------------------
-- Table `Reservas`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `email_cliente` VARCHAR(45) NOT NULL,
  `telefono_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reservas`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas`.`Hotel` (
  `id_hotel` INT NOT NULL AUTO_INCREMENT,
  `nombre_hotel` VARCHAR(45) NOT NULL,
  `direccion_hotel` VARCHAR(45) NOT NULL,
  `categoria_hotel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reservas`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas`.`Habitacion` (
  `id_habitacion` INT NOT NULL AUTO_INCREMENT,
  `tipo_habitacion` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `precio` INT NOT NULL,
  `Hotel_id_hotel` INT NOT NULL,
  PRIMARY KEY (`id_habitacion`, `Hotel_id_hotel`),
  INDEX `fk_Habitacion_Hotel_idx` (`Hotel_id_hotel` ASC) VISIBLE,
  CONSTRAINT `fk_Habitacion_Hotel`
    FOREIGN KEY (`Hotel_id_hotel`)
    REFERENCES `Reservas`.`Hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reservas`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas`.`Reserva` (
  `id_reservas` INT NOT NULL AUTO_INCREMENT,
  `Cliente_id_cliente` INT NOT NULL,
  `Habitacion_id_habitacion` INT NOT NULL,
  `Habitacion_Hotel_id_hotel` INT NOT NULL,
  `fecha_entrada` DATETIME NOT NULL,
  `fecha_salida` DATETIME NOT NULL,
  `cantidad_personas` INT NOT NULL,
  PRIMARY KEY (`id_reservas`, `Cliente_id_cliente`, `Habitacion_id_habitacion`, `Habitacion_Hotel_id_hotel`),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_Reserva_Habitacion1_idx` (`Habitacion_id_habitacion` ASC, `Habitacion_Hotel_id_hotel` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_id_cliente`)
    REFERENCES `Reservas`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Habitacion1`
    FOREIGN KEY (`Habitacion_id_habitacion` , `Habitacion_Hotel_id_hotel`)
    REFERENCES `Reservas`.`Habitacion` (`id_habitacion` , `Hotel_id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
